### ISSUE TITLE
Support for R#9

### ISSUE THREAD

**Issue by MichaelKetting** [JetBrains/resharper-nuget#23]
Please release a new version with added support for R# 9

Many thanks, Michael

**Comment by atrevidogk** [comment]
Would like to see it too.

**Comment by jjmartin** [comment]
++

**Comment by khellang** [comment]
:+1:

**Comment by dnyvik** [comment]
Yes please! :+1:

**Comment by MichaelKetting** [comment]
Matt Ellis posted that he hopes for a release this week.
https://twitter.com/fvilers/status/557823894489681920

**Comment by khellang** [comment]
There's also been talk about bundling the functionality with R# 9.1:

https://twitter.com/serjic/status/560044989842202624

**Comment by citizenmatt** [comment]
Yep, it's going to be rolled into 9.1. The main product already has knowledge of nuget (which it didn't when the plugin was started), so it's a bit weird that we have some functionality in the product, and some in the plugin. This wasn't an issue with 8.x, because we just bundled the plugin, but we didn't get round to that with 9.0, unfortunately (too many changes in the installation process meant it got missed). I'm not sure if there will be a 9.0 release - we're hoping to start the 9.1 EAP soon (it's needed for newer VS2015 and C#6 support).

**Comment by MichaelKetting** [comment]
Great news!

**Comment by jjmartin** [comment]
i found the new function in 9.1.   is there a way to customize the package source?  We have an internal nuget server that i'd like to have added but it doesn't seem to support that...

**Comment by citizenmatt** [comment]
I presume you mean the search on nuget.org action? This isn't customisable - it's not querying nuget.org, but an index that JetBrains has built from every package on nuget.org, and this process can't support custom sources.

**Comment by citizenmatt** [comment]
The functionality for this plugin is now available as a standard feature in 9.1. When ReSharper prompts to add a reference to an assembly that's part of a nuget package, the package is added instead of a direct reference to the assembly.

This plugin is now deprecated.
